version: "3.9"
services:
  db_1:
    image: ghodrat/ms-sql-server:dev-2017-win-lts2022
    ports:
      - "10501:1433"
    environment:
      sa_password: Your_password123
      ACCEPT_EULA: "Y"
    volumes:
      - .\db_1\dbs:C:\Server\MSSQL\DB
      - .\db_1\logs:C:\Server\MSSQL\LOG
      - .\db_1\backups:C:\Server\MSSQL\Backup
    restart: always
